87 - Update end to end tests to test using jobdef json

diff --git a/.github/workflows/end-to-end-test.yml b/.github/workflows/end-to-end-test.yml
--- a/.github/workflows/end-to-end-test.yml
+++ b/.github/workflows/end-to-end-test.yml
@@ -77,6 +77,8 @@ jobs:
 
           docker compose -f ./docker-compose-end-to-end-test.yml logs test-harness | grep -Po "Test Harness test run completed successfully"
 
+          rm ./munin/deploy/config/job_definitions/*.json
+
       - name: Check for performance test failures
         run: |
           # Inspect report output for failures of performance test
@@ -115,6 +117,8 @@ jobs:
           curl 127.0.0.1:8800/isTestRunning | grep 'false'
 
           docker compose -f ./docker-compose-end-to-end-test.yml logs test-harness | grep -Po "Test Harness test run completed successfully"
+          
+          rm ./munin/deploy/config/job_definitions/*.json
 
       - name: Check for functional test failures
         run: |
@@ -139,6 +143,49 @@ jobs:
             echo "No test failures."
             exit 0
           fi
+        
+      - name: Functional test with jobdef json
+        run: |
+          echo "Running a functional test"
+          timeout 1m ./scripts/end-to-end-curl-commands-functional-test-jobdefjson.sh
+
+          # this should return true as tests are running
+          echo "Testing that tests are running"
+          curl 127.0.0.1:8800/isTestRunning | grep 'true'
+
+          # It takes this long to get any meaningful output from the test harness
+          # It's 60 seconds for the test harness to start the job ...
+          # ... and 10 seconds to run the job ...
+          # ... and 60 seconds to ensure the test is finished ...
+          # ... and another 50 seconds for grace time in starting up/waiting for logs/waiting for calculations
+          echo "Sleeping to give the test harness time to work"
+          date
+          sleep 120
+          date
+          curl 127.0.0.1:8800/isTestRunning | grep 'false'
+
+          docker compose -f ./docker-compose-end-to-end-test.yml logs test-harness | grep -Po "Test Harness test run completed successfully"
+          rm ./munin/deploy/config/job_definitions/*.json
+
+      - name: Check for functional test failures job def json
+        run: |
+          # Inspect report output for failures of functional test
+          failures=$(xmllint --xpath 'string(//testsuites/@failures)' ./report_output/functional_test_jobdef/Results.xml)
+
+
+
+          # Print the result
+          echo "failures: $failures"
+
+          # Check if failures is greater than 0
+          if [ "$failures" -ne 0 ]; then
+            echo "There are functional test failures!"
+            exit 1
+          else
+            echo "No test failures."
+            exit 0
+          fi
+
       
       - name: Run tear down procedure
         run: |
